language: csharp
dist: bionic
dotnet: 3.0.100
mono: none

services:
  - docker

env:
  global:
    - BUILD_VERSION_NUMBER="1.0.1.${TRAVIS_BUILD_NUMBER}"
    - PACKAGE_VERSION_NUMBER="${BUILD_VERSION_NUMBER}"
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

before_install:
  - chmod -R a+x ./.build.sh

install:
  - dotnet --version

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      name: 'Execute Project Tests'
      script:
        - dotnet restore --no-cache
        - dotnet test -c Debug --no-restore ./tests/MarsImages.Tests/MarsImages.Tests.csproj
    - stage: build
      name: 'Build Project - Release'
      if: branch = master
      script:
        - ./.build.sh
      if: branch != master
      env:
        - PACKAGE_VERSION_NUMBER="${BUILD_VERSION_NUMBER}-${TRAVIS_BRANCH}"
      script:
        - ./.build.sh

notifications:
  email:
    on_success: never
    on_failure: always